# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/



# Appearance
appearance:
  theme_default: light

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Haowei(Howard) Cao is a Ph.D. candidate in Computer Science .'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: false

# Site footer
footer:
  copyright:
    notice: '© {year} Me. Made on earth by a human'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
